# Generated by Django 5.2 on 2025-04-27 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('master', 'Master'), ('moderator', 'Moderator')], default='client', max_length=20),
        ),
    ]
