# Generated by Django 5.2 on 2025-05-03 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_auth_provider_alter_user_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='auth_provider',
            field=models.CharField(choices=[('EMAIL', 'Email'), ('GOOGLE', 'Google'), ('GITHUB', 'Github')], default='EMAIL', max_length=20),
        ),
    ]
