# Generated by Django 5.2 on 2025-05-04 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_service_center'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecenter',
            name='published',
            field=models.BooleanField(default=True, max_length=255),
        ),
        migrations.AddField(
            model_name='taskcategory',
            name='published',
            field=models.BooleanField(default=True, max_length=255),
        ),
    ]
