# Generated by Django 5.2 on 2025-06-08 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_servicecenter_published_taskcategory_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='tasks.taskcategory'),
        ),
        migrations.AlterField(
            model_name='task',
            name='service_center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='tasks.servicecenter'),
        ),
    ]
